[package]
name = "hdrcopier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
dialoguer = "0.9.0"
nom = "7.1.0"
